feat: added rate limiter
tinkerhub/platform pull request #60
Opened 2022-12-27 14:44 UTC by reenphygeorge

### What does it do?

* Added Rate Limiter for api

### Why is it needed?

* To save the api from brute force attacks

### How to test it?

Just run the api with the command ``pnpm --filter api dev``

2023-01-12 13:06 UTC, sreehari2003 submitted a review, later dismissed

2023-01-13 03:59 UTC, akhilmhdh requested changes

2023-01-13 03:59 UTC, akhilmhdh commented on apps/api/src/app.module.ts
> +      ttl: parseInt(process.env.TIME_TO_LIVE as string, 10),
Add a default value for if not set

2023-01-13 04:41 UTC, akhilmhdh approved these changes

2023-01-13 04:41 UTC, merged